---
title: "Surface Detection by Robot Movements"
author: "Marian Dumitrascu"
date: "March 19, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Surface Detection by Robot Movements


## Introduction

gyros, accelerometer and magnetometer sensor

## Load Libraries

```{r data load, message=FALSE, warning=FALSE}
options(repos="https://CRAN.R-project.org")
# install.packages("ISLR")
# install.packages("orientlib")
# install.packages("RSpincalc")
# devtools::install_github("collectivemedia/tictoc")
# install.packages("kableExtra")
# install.packages("doParallel", dependencies = TRUE)
# install.packages("randomForest", dependencies = TRUE)
# install.packages("rf")
library(readr)
library(tidyverse)
library(ISLR)
library(caret)
library(orientlib)
library(matrixStats)
library(randomForest)
library(RSpincalc)
library(tictoc)
library(kableExtra)

library(doParallel)
library(foreach)

library(nnet)

library(mlbench)

```






```{r}

fitControl <- trainControl(method = "repeatedcv",
  number = 2,
  repeats = 30, 
  returnResamp="all")

tmp_data <- x_train_for_train # %>% slice(1:500)
x_c5 <- tmp_data %>% select(-series_id, -surface) 
y_c5 <- tmp_data$surface 
rm(tmp_data)

grid <- expand.grid( .winnow = c(TRUE), .trials=c(10,15,20, 25, 30, 35), .model="tree" )

model_fit <- train(
										x=x_c5,
										y=y_c5,
										tuneGrid=grid,
										trControl=fitControl,
										method="C5.0",
										verbose=FALSE)

model_fit

# visualize the resample distributions
xyplot(model_fit,type = c("g", "p", "smooth"))

y_hat <- predict(model_fit, select(x_train_for_test, -series_id))
conf_matrix <- confusionMatrix(y_hat, x_train_for_test$surface)
conf_matrix$overall["Accuracy"]

rm(x_c5, y_c5)

y_hat <- predict(model_fit, select(x_test_processed, -series_id))

x_test_processed_for_submission <- x_test_processed %>% select(series_id) %>% mutate(surface = y_hat)
write_csv(x_test_processed_for_submission, "data/submission_C50_03.csv")


```


```{r}
library(plyr)
library(recipes)
library(dplyr)


C5CustomSort <- function(x) {
  
  x$model <- factor(as.character(x$model), levels = c("rules","tree"))
  x[order(x$trials, x$model, x$splits, !x$winnow),]

}

C5CustomLoop <- function (grid) 
{
    loop <- ddply(grid, c("model", "winnow","splits"), function(x) c(trials = max(x$trials)))
    submodels <- vector(mode = "list", length = nrow(loop))
    for (i in seq(along = loop$trials)) {
        index <- which(grid$model == loop$model[i] & grid$winnow == 
            loop$winnow[i] & grid$splits == loop$splits[i])
        trials <- grid[index, "trials"]
        submodels[[i]] <- data.frame(trials = trials[trials != 
            loop$trials[i]])
    }
    list(loop = loop, submodels = submodels)
}

C5CustomGrid <- function(x, y, len = NULL) {
  c5seq <- if(len == 1)  1 else  c(1, 10*((2:min(len, 11)) - 1))
  expand.grid(trials = c5seq, splits = c(2,10,20,50), winnow = c(TRUE, FALSE), model = c("tree","rules"))
}

C5CustomFit <- function(x, y, wts, param, lev, last, classProbs, ...) {
  # add the splits parameter to the fit function
  # minCases is a function of splits
  
  theDots <- list(...)

  splits   <- param$splits
  minCases <- floor( length(y)/splits ) - 1

  if(any(names(theDots) == "control"))
	{
    theDots$control$winnow        <- param$winnow
    theDots$control$minCases      <- minCases
    theDots$control$earlyStopping <- FALSE
  }
  else
  theDots$control <- C50::C5.0Control(winnow = param$winnow, minCases = minCases, earlyStopping=FALSE )

  argList <- list(x = x, y = y, weights = wts, trials = param$trials, rules = param$model == "rules")

  argList <- c(argList, theDots)

  # do.call("C50::C5.0.default", argList)
  C50::C5.0.default(x = x, y = y, weights = wts, trials = param$trials, rules = param$model == "rules", theDots)

}
GetC5Info <- function() {

  # get the default C5.0 model functions
  c5ModelInfo <- getModelInfo(model = "C5.0", regex = FALSE)[[1]]

  # modify the parameters data frame so that it includes splits
  c5ModelInfo$parameters$parameter <- factor(c5ModelInfo$parameters$parameter,levels=c(levels(c5ModelInfo$parameters$parameter),'splits'))
  c5ModelInfo$parameters$label <- factor(c5ModelInfo$parameters$label,levels=c(levels(c5ModelInfo$parameters$label),'Splits'))
  c5ModelInfo$parameters <- rbind(c5ModelInfo$parameters,c('splits','numeric','Splits'))
  
  # replace the default c5.0 functions with ones that are aware of the splits parameter
  c5ModelInfo$fit  <- C5CustomFit
  c5ModelInfo$loop <- C5CustomLoop
  c5ModelInfo$grid <- C5CustomGrid
  c5ModelInfo$sort <- C5CustomSort

  return (c5ModelInfo)

}

c5info <- GetC5Info()

# Define the structure of cross validation
fitControl <- trainControl(method = "repeatedcv", number = 10,  repeats = 10)
 
# create a custom cross validation grid
grid <- expand.grid( .winnow = c(TRUE, FALSE), .trials=c(1,5,10,15,20), .model=c("tree"), .splits=c(2,5,10,15,20,25,50,100) )

tmp_data <- x_train_for_train  %>% slice(1:500)
x_c5 <- tmp_data %>% select(-series_id, -surface) 
y_c5 <- tmp_data$surface 
rm(tmp_data)

# Tune and fit model
model_fit <- train(x=x_c5,y=y_c5,tuneGrid=grid,trControl=fitControl,method=c5info,verbose=FALSE)

model_fit
		  
plot(model_fit)

y_hat <- predict(model_fit, select(x_train_for_test, -series_id))
conf_matrix <- confusionMatrix(y_hat, x_train_for_test$surface)
conf_matrix$overall["Accuracy"]

rm(x_c5, y_c5)

```





```{r}
y_hat <- predict(model_fit, select(x_test_processed, -series_id))

x_test_processed_for_submission <- x_test_processed %>% select(series_id) %>% mutate(surface = y_hat)
write_csv(x_test_processed_for_submission, "data/submission_C50_03.csv")
```

