---
title: "Surface Detection by Robot Movements"
author: "Marian Dumitrascu"
date: "March 19, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

For this project I choosed a Kaggle.com open competion project. This is [*CareerCon 2019 - Help Navigate Robots*](https://www.kaggle.com/c/career-con-2019). Here is the description of the project from Kaggle:


> *In this competition, you’ll help robots recognize the floor surface they’re standing on using data collected from Inertial Measurement Units (IMU sensors).*
> *We’ve collected IMU sensor data while driving a small mobile robot over different floor surfaces on the university premises. The task is to predict which one of the nine floor types (carpet, tiles, concrete) the  robot is on using sensor data such as acceleration and velocity. Succeed and you'll help improve the navigation of robots without assistance across many different surfaces, so they won’t fall down on the job.*

The task is challenging, but I believe I can obtain a decent result using techniques and tools learned in this course.

In this document I will:

	1. describe data provided and output expected
	2. perform data analysis, visualization and get insights
	3. pre-process and transform data
	4. decide the model to use, measure its performance and tune it
	5. perform the final data prediction and show the results, submit to Kaggle
	6. draw some conclusions

I also keep this project on GitHub here: https://github.com/mariandumitrascu/ph125_9_HelpRobotsNavigate

# Data Description

# Data Analysis

I will make the following assumptions about observations:

* all observations are made using the same robot
* the interval between obseervations is always the same. 
* the surface is a plane, no stairs, hills or valleys

From a physicyst perrspective there are three forces involved: gravitation force, robot propulsion and friction force. Gravitation force is constant. Friction force depends on the surface by a coefficient and propulsion is an unknown variable. We need to basically determine the friction coeeficient based on a movement pattern. 

## First Insights

## Data Distribution

# Data Pre-Processing

## Quaternion to Euler

## More Data Analysis

# Fit The Model

## One-vs-One or One-vs-All

# Results and Submit the Data

# Conclusion

# Reference

1. Q2EA: Convert from rotation Quaternions to Euler Angles. Q2EA converts from Quaternions (Q) to Euler Angles (EA) based on D. M. Henderson (1977). Q2EA.Xiao is the algorithm by J. Xiao (2013) for the Princeton Vision Toolkit. https://rdrr.io/cran/RSpincalc/man/Q2EA.html

2. Understanding Quaternions. http://www.chrobotics.com/library/understanding-quaternions

3. Understanding Euler Angles. http://www.chrobotics.com/library/understanding-euler-angles

4. Tune Machine Learning Algorithms in R (random forest case study) by Jason Brownlee. https://machinelearningmastery.com/tune-machine-learning-algorithms-in-r/

5. Classification with more than two classes, from Introduction to Information Retrieval, Christopher D. Manning, Prabhakar Raghavan and Hinrich Schütze,, Cambridge University Press 2008  https://nlp.stanford.edu/IR-book/html/htmledition/classification-with-more-than-two-classes-1.html
