---
title: "Surface Detection by Robot Movements"
author: "Marian Dumitrascu"
date: "March 19, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Surface Detection by Robot Movements


## Introduction



## Data Analysis

You can include R code in the document as follows:

```{r data load}
# install.packages("ISLR")
# install.packages("orientlib")
library(readr)
library(tidyverse)
library(ISLR)
library(caret)
library(orientlib)

x_train <- read_csv("data/X_train.csv")
y_train <- read_csv("data/y_train.csv")
```


```{r}
x <- quaternion(c(1,2,3,0.5))

```


```{r data analysis}

head(x_train)
head(y_train)

train_set <- x_train %>% left_join(y_train, by = "series_id")
train_df <- as.data.frame(train_set)
# train_df[is.na(train_df)]
head(train_df, 200)

```
```{r}
train_set <- train_set %>% 
	mutate(xy = sqrt(linear_acceleration_X^2 + linear_acceleration_Y^2), z = linear_acceleration_Z)
train_df <- as.data.frame(train_set)

train_df %>% group_by(surface) %>% 
	summarize(measuremeent = n_distinct(series_id))

```


```{r}
# head(train_set)
train_tmp <- train_df %>% 
	filter(surface == 'hard_tiles_large_space') %>% 
	filter(series_id %in% c(8, 21, 29, 63, 98, 119))
	

# top_n(4, measurement_number)




train_tmp %>% ggplot(aes(xy, z)) +
	geom_path() +
	facet_wrap(~series_id + group_id) 

```

```{r}
series <- train_df %>% 
	filter(surface == 'hard_tiles') %>% 
	group_by(series_id) %>% summarize(n = n()) 

series <- series %>% slice(1:6) %>% pull(series_id)
	
train_tmp <- train_df %>% 
	filter(series_id %in% series)

train_tmp %>% ggplot(aes(x, z)) +
	geom_path() +
	facet_wrap(~series_id + group_id) 
```

```{r}
series <- train_df %>% 
	filter(surface == 'carpet') %>% 
	group_by(series_id) %>% summarize(n = n()) 

series <- series %>% slice(1:6) %>% pull(series_id)
	
train_tmp <- train_df %>% 
	filter(series_id %in% series)


train_tmp %>% ggplot(aes(xy, z)) +
	geom_path() +
	facet_wrap(~series_id + group_id) 
```
## Show path movements during one obs.

```{r}

# t1 <- train_df %>% 
# 	# filter(series_id == 37) %>% 
# 	select(orientation_X, orientation_Y, orientation_Z, orientation_W, angular_velocity_X,angular_velocity_Y, angular_velocity_Z, linear_acceleration_X, linear_acceleration_Y, linear_acceleration_Z)

# select only the columns that we want for just one measurement
i <- 37 # carpet
i <- 13 # carpet
i <- 15 # carpet
i <- 119 # hard_tiles_large_space
t0 <- train_df %>% filter(series_id == i)
t1 <- train_df %>% 
	filter(series_id == i) %>% 
	select(linear_acceleration_X, linear_acceleration_Y, linear_acceleration_Z)

# do PCA, this should rotate
t11 <- prcomp(t1)
summary(t11)

t23 <- bind_cols(as_data_frame(t11$x), data_frame(series_id = t0$series_id))
t23 %>% ggplot(aes(PC1, PC2)) +
	geom_path()
```
## PCA Over all components

```{r}
t1 <- train_df %>% 
	filter(series_id == 21) %>% 
	select(
		orientation_X, orientation_Y, orientation_Z, orientation_W, 
		angular_velocity_X, angular_velocity_Y, angular_velocity_Z,
		linear_acceleration_X, linear_acceleration_Y, linear_acceleration_Z)

t2 <- prcomp(as.matrix(t1))
summary(t2)
class(t2$x)

t3 <- as_data_frame(t2$x) %>% select(PC1, PC2, PC3, PC4, PC5)
pca1 <- prcomp(t3)
summary(pca1)

```


```{r}
# 3800 observations
# 
measurement_numbers <- train_df %>% slice(1:128) %>% pull(measurement_number)
mn_02 <- as.character(1000 + measurement_numbers)
# class(measurement_numbers)

train_02 <- train_df %>%
	group_by(series_id) %>% 
	summarize(surface = first(surface)) %>% 
	slice(1:500)

t_01 <- data.frame(measurement_numbers = NULL,  r = NULL, series_id = NULL)


for (s_id in train_02$series_id)
{
	# print(s_id)
	obj_01 <- train_df %>%  
		filter(series_id == s_id)
	obj_02 <- obj_01 %>% 
		select(
		# orientation_X, orientation_Y, orientation_Z, orientation_W, 
		angular_velocity_X, angular_velocity_Y, angular_velocity_Z,
		linear_acceleration_X, linear_acceleration_Y, linear_acceleration_Z)
	pca <- prcomp(obj_02)
	# print(summary(pca))
	x <- as_data_frame(pca$x)
	r <- sqrt(x$PC1^2 + x$PC2^2 + x$PC3^2)
	# r <- sqrt(x$PC1^2 + x$PC2^2)
	# r <- (r - min(r))/(max(r) - min(r))
	t_03 <- data.frame(measurement_numbers = mn_02, r = r, series_id = s_id)
	t_01 <- bind_rows(t_01, t_03)
	
		
}

t_02 <- t_01 %>% spread(measurement_numbers, r)

t_num <-  t_02 %>% select(-series_id)
pca_02 <- prcomp(as_data_frame(t_num))
# summary(pca_02)

x <- as_data_frame(pca_02$x[, 1:10])
t_04 <- bind_cols(x, data_frame(surface = train_02$surface))
# t_04 <- t_04 %>% mutate(surface = factor(levels(t_04$surface)))
# 
t_04 <- t_04 %>% mutate(surface = as.factor(surface))


test_index <- createDataPartition(y = t_04$PC1, times = 1, p = 0.1, list = FALSE)
train_10 <- t_04[-test_index, ]
test_10 <- t_04[test_index, ]

# t_04 %>% ggplot(aes(PC1, PC2, fill = surface)) +
# 	geom_point(aes(color = surface)) +
# 	geom_point(cex=3, pch=21) +
#   coord_fixed(ratio = 1)
```

```{r}

# install.packages("ISLR")
fit <- train(surface ~ .,  method = "knn", 
             tuneGrid = data.frame(k = seq(10, 90, 2)), 
             data = train_10)
ggplot(fit) 

fit <- train(surface ~ ., method = "knn", data = test_10, k = 36)



# y_hat <- predict(fit$finalModel, test_10, type = "class")
y_hat <- predict(fit$finalModel, test_10, type = "class")
confusionMatrix(y_hat, test_10$surface)$overall["Accuracy"]
```

```{r}
train_rpart <- train(surface ~ ., 
                     method = "rpart",
                     tuneGrid = data.frame(cp = seq(0, 0.05, len = 25)),
                     data = train_10)
ggplot(train_rpart)

confusionMatrix(predict(train_rpart, test_10), test_10$surface)$overall["Accuracy"]
```


```{r}
library(randomForest)
fit <- randomForest(surface ~., data = train_10) 

```




```{r}
fit <- train(surface ~ PC1 + PC2, method = "qda", data = train_10)
y_hat <- predict(fit, test_10, type = "raw")
y_test <- test_10$surface

sum(y_hat == y_test)/nrow(test_10)
```




```{r}

fit_knn3 <- knn3(surface ~ ., data = train_10, k = 37)
y_hat <- predict(fit_knn3, test_10, type = "class")
y_test <- test_10$surface

sum(y_hat == y_test)/nrow(test_10)

createFolds()


```

